# These substitutions allow the end user to override certain values
substitutions:
  devicename: radar-test
  upper_devicename: radar_test

esphome:
  name: $devicename
  friendly_name: $upper_devicename

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0 # deactivated because its used by the radar sensor

# Enable Home Assistant API
api:
  encryption:
    key: "apiPW" # Change to your device

web_server:
  port: 80
  #version: 1

ota:
  password: "otaPW" # Change to your device if necessary


wifi:
  ssid: !secret wifi_ssid # Has to be set up in the secrets.yaml
  password: !secret wifi_password # Has to be set up in the secrets.yaml

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Radar-Test Fallback Hotspot"
    password: "12345678"

captive_portal:

uart:
  # id: uart1 # not necessary to name
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  timeout: 30s
  max_move_distance : 3m
  max_still_distance: 3m

sensor:
  - platform: ld2410
    moving_distance:
      name : $devicename Moving Distance
    still_distance:
      name: $devicename Still Distance
    moving_energy:
      name: $devicename Move Energy
    still_energy:
      name: $devicename Still Energy
    detection_distance:
      name: $devicename Detection Distance

binary_sensor:
  - platform: ld2410
    has_target:
      name: $devicename Presence
    has_moving_target:
      name: $devicename Moving Target
    has_still_target:
      name: $devicename Still Target